#-------------------------------------------------------------------------------
#
# This file is part of the SamlBundle.
#
# (c) Paulo Dias <dias.paulo@gmail.com>
#
#-------------------------------------------------------------------------------
saml_login:
    path: /login-saml
    defaults:
        _controller: SamlBundle:Security:login

saml_login_check:
    path: /login-check-saml
    defaults:
        _controller: SamlBundle:Security:check

saml_logout:
    path: /logout-saml
    defaults:
        _controller: SamlBundle:Security:logout
