#-------------------------------------------------------------------------------
#
# This file is part of the SamlBundle.
#
# (c) Paulo Dias <dias.paulo@gmail.com>
#
#-------------------------------------------------------------------------------
services:
    samlauth.service:
        class: PDias\SamlBundle\Saml\SamlAuth
        file: %saml.autoload_path%
        public: false
        arguments:
            - %saml.service_provider%
        calls:
            - [setAuthenticationField, ["%saml.authentication_field%"]]
