#-------------------------------------------------------------------------------
#
# This file is part of the SamlBundle.
#
# (c) Paulo Dias <dias.paulo@gmail.com>
#
#-------------------------------------------------------------------------------
services:
    saml.security.authentication.provider:
        class: PDias\SamlBundle\Security\Authentication\Provider\SamlProvider
        arguments: ['', %kernel.cache_dir%/security/nonces]

    saml.security.authentication.listener:
        class: PDias\SamlBundle\Security\Firewall\SamlListener
        arguments: [@security.context, @security.authentication.manager, %saml.service_provider%, %saml.authentication_field%, @event_dispatcher]

    saml.service.user.provider:
        class: PDias\SamlBundle\Security\User\SamlUserProvider
        arguments:
            - %saml.service_provider%
            - %saml.autoload_path%

    saml.security.http.logout:
        class: PDias\SamlBundle\Security\Http\Logout\SamlLogoutHandler
        arguments:
            - %saml.service_provider%
