#-------------------------------------------------------------------------------
#
# This file is part of the SamlBundle.
#
# (c) Paulo Dias <paulo.dias@ipcb.pt>
#
#-------------------------------------------------------------------------------
parameters:
    saml.service.user.provider.class: SamlBundle\Security\User\SamlUserProvider
    saml.security.authentication.provider.class: SamlBundle\Security\Authentication\Provider\SamlProvider
    saml.security.firewall.listener.class: SamlBundle\Security\Firewall\SamlListener
    saml.security.http.logout.handler.class: SamlBundle\Security\Http\Logout\SamlLogoutHandler

services:
    saml.security.authentication.provider:
        class: "%saml.security.authentication.provider.class%"
        arguments: ['', %kernel.cache_dir%/security/nonces]

    saml.security.authentication.listener:
        class: "%saml.security.firewall.listener.class%"
        arguments: [@security.context, @security.authentication.manager, %saml.service_provider%, @event_dispatcher]

    saml.service.user.provider:
        class: %saml.service.user.provider.class%
        arguments:
            - %saml.service_provider%
            - %saml.autoload_path%

    saml.security.http.logout:
        class: "%saml.security.http.logout.handler.class%"
        arguments:
            - %saml.service_provider%